import logging
SETTINGS_PRIORITY = 1

PYFORMS_STYLESHEET = 'style.css'
PYFORMS_STYLESHEET_LINUX = 'style.css'
PYFORMS_LOG_HANDLER_FILE_LEVEL = logging.DEBUG
PYFORMS_LOG_HANDLER_CONSOLE_LEVEL = logging.INFO
