time_blocks:
    # SLEEP HOURS / EARLY MORNING
    - 12:10AM-12:35AM # 10 min break after
    - 12:45AM-1:10AM
    - 1:15AM-1:40AM
    - 1:45AM-2:10AM # 10 min break after
    - 2:20AM-2:45AM
    - 2:50AM-3:15AM
    - 3:20AM-3:45AM # 10 min break after
    - 3:55AM-4:20AM
    - 4:25AM-4:50AM
    - 4:55AM-5:20AM # breakfast after (30 mins)
    - 5:50AM-6:15AM
    - 6:20AM-6:45AM
    - 6:50AM-7:15AM # 10 min break after
    - 7:25AM-7:50AM
    - 7:55AM-8:20AM
    - 8:25AM-8:50AM # 10 min break after
    # MORNING
    - 9:00AM-9:25AM
    - 9:30AM-9:55AM
    - 10:00AM-10:25AM # 10 min break after
    - 10:35AM-11:00AM
    - 11:05AM-11:30AM
    - 11:35AM-12:00PM # lunch after (30 mins)
    - 12:30PM-12:55PM
    - 1:00PM-1:25PM
    - 1:30PM-1:55PM # 10 min break after
    - 2:05PM-2:30PM
    - 2:35PM-3:00PM
    - 3:05PM-3:30PM # 10 min break after
    - 3:40PM-4:05PM
    - 4:10PM-4:35PM
    - 4:40PM-5:05PM # dinner after (30 mins)
    # EVENING
    - 5:35PM-6:00PM
    - 6:05PM-6:30PM
    - 6:35PM-7:00PM # 10 min break after
    - 7:10PM-7:35PM
    - 7:40PM-8:05PM
    - 8:10PM-8:35PM # 10 min break after
    - 8:45PM-9:10PM
    - 9:15PM-9:40PM
    - 9:45PM-10:10PM # 10 min break after
    - 10:20PM-10:45PM
    - 10:50PM-11:15PM
    - 11:20PM-11:45PM # late night snack after (25 mins)
